{
 "title": "Demo Badge - Sensor Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ambient Light",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "region": "default",
     "database": "\"SensorData\"",
     "table": "\"Badge\"",
     "measure": "light",
     "queryMode": "Metrics",
     "rawQuery": "SELECT measure_value::bigint FROM $__database.$__table WHERE $__timeFilter and measure_name = '$__measure' ",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Ambient Light",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "region": "default",
     "database": "\"SensorData\"",
     "measure": "light",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, measure_value::bigint as MQTT FROM \"SensorData\".\"Badge\" WHERE source='mqtt' and measure_name='light'",
     "statistic": "Average",
     "table": "\"Badge\""
    },
    {
     "database": "\"SensorData\"",
     "measure": "humidity",
     "rawQuery": "SELECT time, measure_value::bigint as Sidewalk FROM \"SensorData\".\"Badge\" WHERE source='sidewalk' and measure_name='light'",
     "table": "\"Badge\""
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "region": "default",
     "database": "\"SensorData\"",
     "table": "\"Badge\"",
     "measure": "humidity",
     "queryMode": "Metrics",
     "rawQuery": "SELECT measure_value::double FROM $__database.$__table WHERE $__timeFilter and measure_name = '$__measure' ",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "database": "\"SensorData\"",
     "measure": "humidity",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, measure_value::double as MQTT FROM \"SensorData\".\"Badge\" WHERE source='mqtt' and measure_name='humidity'",
     "region": "default",
     "statistic": "Average",
     "table": "\"Badge\""
    },
    {
     "database": "\"SensorData\"",
     "measure": "humidity",
     "rawQuery": "SELECT time, measure_value::double as Sidewalk FROM \"SensorData\".\"Badge\" WHERE source='sidewalk' and measure_name='humidity'",
     "table": "\"Badge\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"SensorData\"",
     "measure": "temperature",
     "queryMode": "Metrics",
     "rawQuery": "SELECT measure_value::double FROM $__database.$__table WHERE $__timeFilter and measure_name = '$__measure' ",
     "region": "default",
     "statistic": "Average",
     "table": "\"Badge\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"SensorData\"",
     "measure": "temperature",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, measure_value::double as MQTT FROM \"SensorData\".\"Badge\" WHERE source='mqtt' and measure_name='temperature'",
     "region": "default",
     "statistic": "Average",
     "table": "\"Badge\""
    },
    {
     "database": "\"SensorData\"",
     "measure": "humidity",
     "rawQuery": "SELECT time, measure_value::double as Sidewalk FROM \"SensorData\".\"Badge\" WHERE source='sidewalk' and measure_name='temperature'",
     "table": "\"Badge\""
    }
   ]
  }
 ]
}