{
 "title": "SidewalkGrafanaApplication",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device_registration_state", "query": "device_registration_state" },
   { "name": "message_delivery_status", "query": "message_delivery_status" },
   { "name": "proximity", "query": "proximity" },
   { "name": "uplink", "query": "uplink" },
   { "name": "wireless_device_id" }
  ]
 },
 "panels": [
  { "title": "Sidewalk messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# uplink",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "# device_registration_state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Events distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"SidewalkSample\"",
     "measure": "uplink",
     "rawQuery": "SELECT count(*) as ${uplink} FROM $__database.$__table\r\nWHERE $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"UplinkMessages\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT count(*) as ${message_delivery_status} FROM $__database.$__table\r\nWHERE notification='${message_delivery_status}' and $__timeFilter\r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT count(*) as ${proximity} FROM $__database.$__table\r\nWHERE notification='${proximity}' and $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT count(*) as ${device_registration_state} FROM $__database.$__table\r\nWHERE notification='${device_registration_state}' and $__timeFilter\r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='') ",
     "table": "\"Notifications\""
    }
   ]
  },
  {
   "title": "Uplink messages",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "database": "\"SidewalkSample\"",
     "measure": "uplink",
     "rawQuery": "SELECT time, wireless_device_id, payload_base64, payload \r\nFROM $__database.$__table\r\nWHERE $__timeFilter\r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"UplinkMessages\""
    }
   ]
  },
  {
   "title": "# proximity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "# message_delivery_status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"SidewalkSample\"",
     "measure": "uplink",
     "rawQuery": "SELECT time, 3 as ${uplink} FROM $__database.$__table\r\nWHERE $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"UplinkMessages\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT time, 1 as ${device_registration_state} FROM $__database.$__table\r\nWHERE notification='${device_registration_state}' AND $__timeFilter\r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT time, 2 as ${proximity} FROM $__database.$__table\r\nWHERE notification='${proximity}' AND $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    },
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT time, 4 as ${message_delivery_status} FROM $__database.$__table\r\nWHERE notification='${message_delivery_status}' AND $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "database": "\"SidewalkSample\"",
     "measure": "notification",
     "rawQuery": "SELECT time, wireless_device_id, notification, event_type\r\nFROM $__database.$__table\r\nWHERE $__timeFilter \r\nAND (wireless_device_id = '${wireless_device_id}' OR '${wireless_device_id}'='')",
     "table": "\"Notifications\""
    }
   ]
  }
 ]
}